version: '3'
services:

    postgres:
        image: postgres
        container_name: postgres
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata
            - POSTGRES_USER=postgres
#            - PGHOST=postgres
            - POSTGRES_PASSWORD=postgres1G5
            - POSTGRES_DB=postgres
#            - PGPORT=5432
#            - PGSSLMODE=disable
        ports:
            - "5432:5432"
        volumes:
            - ./postgres-data:/var/lib/postgresql/data/pgdata
